//! Static inventory of every public TokenZero operation (tokenzero-irx9.1).

use serde_json::json;

use super::schemas::{
    args, batch_schema, cache_pack_schema, codemode_describe_schema, codemode_search_schema,
    default_results, edit_schema, execute_code_schema, expand_schema, fetch_schema, glob_schema,
    no_args_schema, read_schema, recall_schema, ref_first_results, report_tool_issue_schema,
    rewrite_schema, search_schema, shell_schema, text_schema, tree_schema,
};
use super::types::{
    CapabilityRequirement, CancellationSemantics, CostClass, DomainErrorKind, MigrationStatus,
    Mutability, Operation, RefOwnership, SurfaceExposure,
};

fn read_errors() -> &'static [DomainErrorKind] {
    &[
        DomainErrorKind::Validation,
        DomainErrorKind::Substrate,
        DomainErrorKind::NotFound,
        DomainErrorKind::DeadlineExceeded,
        DomainErrorKind::Cancelled,
        DomainErrorKind::Busy,
        DomainErrorKind::Unauthorized,
        DomainErrorKind::Policy,
    ]
}

fn search_errors() -> &'static [DomainErrorKind] {
    &[
        DomainErrorKind::Validation,
        DomainErrorKind::InvalidPattern,
        DomainErrorKind::Substrate,
        DomainErrorKind::DeadlineExceeded,
        DomainErrorKind::Cancelled,
        DomainErrorKind::Busy,
        DomainErrorKind::Unauthorized,
    ]
}

fn edit_errors() -> &'static [DomainErrorKind] {
    &[
        DomainErrorKind::Validation,
        DomainErrorKind::Policy,
        DomainErrorKind::HunkNotFound,
        DomainErrorKind::AmbiguousHunk,
        DomainErrorKind::NoOpHunk,
        DomainErrorKind::Substrate,
        DomainErrorKind::DeadlineExceeded,
        DomainErrorKind::Cancelled,
        DomainErrorKind::Unauthorized,
    ]
}

fn shell_errors() -> &'static [DomainErrorKind] {
    &[
        DomainErrorKind::Validation,
        DomainErrorKind::Policy,
        DomainErrorKind::Approval,
        DomainErrorKind::Sandbox,
        DomainErrorKind::Runtime,
        DomainErrorKind::DeadlineExceeded,
        DomainErrorKind::Cancelled,
        DomainErrorKind::Busy,
        DomainErrorKind::Unauthorized,
    ]
}

fn expand_errors() -> &'static [DomainErrorKind] {
    &[
        DomainErrorKind::Validation,
        DomainErrorKind::InvalidRef,
        DomainErrorKind::NotFound,
        DomainErrorKind::Substrate,
        DomainErrorKind::DeadlineExceeded,
        DomainErrorKind::Cancelled,
    ]
}

fn fetch_errors() -> &'static [DomainErrorKind] {
    &[
        DomainErrorKind::Validation,
        DomainErrorKind::InvalidUrl,
        DomainErrorKind::Runtime,
        DomainErrorKind::Policy,
        DomainErrorKind::DeadlineExceeded,
        DomainErrorKind::Cancelled,
    ]
}

/// Runtime builder: `json!` schemas are owned Values, so the registry is
/// materialized once via `OnceLock` and sorted by canonical name.
pub fn all_operations() -> &'static [Operation] {
    use std::sync::OnceLock;
    static REG: OnceLock<Vec<Operation>> = OnceLock::new();
    REG.get_or_init(build_registry).as_slice()
}

pub fn operation_by_name(name: &str) -> Option<&'static Operation> {
    all_operations().iter().find(|op| op.name == name)
}

fn build_registry() -> Vec<Operation> {
    let mut ops = vec![
        // --- Classic domain tools (FastMCP + CodeMode bindings) ---
        Operation {
            name: "tz_read",
            description: "Read file(s) under allowed roots: compact visible output plus exact tz:// recovery refs.",
            aliases: &["read"],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Medium,
            ref_ownership: RefOwnership::Blob,
            cancellation: CancellationSemantics::Deadline,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.read"),
                resource_uri: None,
            },
            capabilities: &["read", "exact-refs", "line-range", "shared-cas"],
            cluster: "material",
            args: args(read_schema()),
            results: ref_first_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_find",
            description: "Search file contents for a literal substring and return compact, recoverable matches.",
            aliases: &["find"],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Medium,
            ref_ownership: RefOwnership::Blob,
            cancellation: CancellationSemantics::Deadline,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.find"),
                resource_uri: None,
            },
            capabilities: &["search", "literal", "exact-refs", "shared-cas"],
            cluster: "material",
            args: args(search_schema("Literal substring to search for.")),
            results: ref_first_results(),
            error_kinds: search_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_grep",
            description: "Grep-style exact-first content search: regex when ripgrep is active, literal otherwise.",
            aliases: &["grep"],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Medium,
            ref_ownership: RefOwnership::Blob,
            cancellation: CancellationSemantics::Deadline,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.grep"),
                resource_uri: None,
            },
            capabilities: &["search", "regex", "exact-refs", "shared-cas"],
            cluster: "material",
            args: args(search_schema(
                "Search pattern: regex under the ripgrep backend, literal substring under the internal fallback.",
            )),
            results: ref_first_results(),
            error_kinds: search_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_recall",
            description: "Search every payload already stored in the recovery cache.",
            aliases: &["recall"],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::Blob,
            cancellation: CancellationSemantics::Cooperative,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.recall"),
                resource_uri: None,
            },
            capabilities: &["search", "cache", "exact-refs", "shared-cas"],
            cluster: "material",
            args: args(recall_schema()),
            results: ref_first_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_batch",
            description: "Run several TokenZero ops in one call: one combined capsule, per-op sections, unioned refs.",
            aliases: &["batch"],
            mutability: Mutability::WorkspaceMutating,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Heavy,
            ref_ownership: RefOwnership::Multi,
            cancellation: CancellationSemantics::Deadline,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.batch"),
                resource_uri: None,
            },
            capabilities: &["batch", "exact-refs"],
            cluster: "execution",
            args: args(batch_schema()),
            results: ref_first_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_fetch",
            description: "Fetch an http(s) URL via curl with a TTL cache and exact tz:// refs.",
            aliases: &["fetch"],
            mutability: Mutability::StoreOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Heavy,
            ref_ownership: RefOwnership::Blob,
            cancellation: CancellationSemantics::Deadline,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.fetch"),
                resource_uri: None,
            },
            capabilities: &["fetch", "web", "cache", "exact-refs"],
            cluster: "web",
            args: args(fetch_schema()),
            results: ref_first_results(),
            error_kinds: fetch_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_glob",
            description: "List file paths matching a glob pattern (no contents).",
            aliases: &["glob"],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::Blob,
            cancellation: CancellationSemantics::Cooperative,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.glob"),
                resource_uri: None,
            },
            capabilities: &["discover", "glob", "shared-cas"],
            cluster: "material",
            args: args(glob_schema()),
            results: ref_first_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({ "pattern": ["glob", "query"] }),
        },
        Operation {
            name: "tz_tree",
            description: "Inspect a bounded directory tree for orientation.",
            aliases: &["tree"],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::Blob,
            cancellation: CancellationSemantics::Cooperative,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.tree"),
                resource_uri: None,
            },
            capabilities: &["discover", "tree", "shared-cas"],
            cluster: "material",
            args: args(tree_schema()),
            results: ref_first_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_edit",
            description: "Apply multi-hunk find/replace edits to one file atomically with undo via tz:// ref.",
            aliases: &["edit"],
            mutability: Mutability::WorkspaceMutating,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Medium,
            ref_ownership: RefOwnership::Blob,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.edit"),
                resource_uri: None,
            },
            capabilities: &["write", "atomic", "exact-refs"],
            cluster: "edit",
            args: args(edit_schema()),
            results: ref_first_results(),
            error_kinds: edit_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_shell",
            description: "Run a local command: compact output, exact stream refs, command_success telemetry.",
            aliases: &["shell"],
            mutability: Mutability::WorkspaceMutating,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Heavy,
            ref_ownership: RefOwnership::Blob,
            cancellation: CancellationSemantics::Deadline,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.shell"),
                resource_uri: None,
            },
            capabilities: &["shell", "exact-refs", "command-success"],
            cluster: "execution",
            args: args(shell_schema()),
            results: ref_first_results(),
            error_kinds: shell_errors(),
            arg_aliases: json!({
                "command": ["cmd", "input", "script"],
                "argv": ["args"],
                "timeout_seconds": ["timeout_secs", "timeout", "shell_timeout_seconds"]
            }),
        },
        Operation {
            name: "tz_ingest",
            description: "Store external text behind exact tz:// refs and return a compact capsule.",
            aliases: &["ingest"],
            mutability: Mutability::StoreOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::Blob,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.ingest"),
                resource_uri: None,
            },
            capabilities: &["ingest", "exact-refs"],
            cluster: "execution",
            args: args(text_schema("External text payload to store behind exact refs.")),
            results: ref_first_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({ "text": ["input"] }),
        },
        Operation {
            name: "tz_expand",
            description: "Recover exact bytes from a tz://, fz://, or gz:// ref.",
            aliases: &["expand"],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::Blob,
            cancellation: CancellationSemantics::Deadline,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.token.expand"),
                resource_uri: None,
            },
            capabilities: &[
                "expand",
                "exact-refs",
                "fragment-selectors",
                "symbol-anchors",
                "diff-baseline",
                "shared-cas",
            ],
            cluster: "material",
            args: args(expand_schema()),
            results: ref_first_results(),
            error_kinds: expand_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_mem",
            description: "Inspect local recovery-cache and configuration state.",
            aliases: &["mem"],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.mem"),
                resource_uri: None,
            },
            capabilities: &["diagnostic", "cache"],
            cluster: "execution",
            args: args(no_args_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_cache_pack",
            description: "Build a daemonless prompt-cache pack with a stable prefix and volatile refs.",
            aliases: &["cache_pack", "cache-pack"],
            mutability: Mutability::StoreOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Medium,
            ref_ownership: RefOwnership::Multi,
            cancellation: CancellationSemantics::Cooperative,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.cache_pack"),
                resource_uri: None,
            },
            capabilities: &["cache", "prompt-cache"],
            cluster: "execution",
            args: args(cache_pack_schema()),
            results: ref_first_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_rewrite",
            description: "Plan a conservative TokenZero-safe rewrite of a shell command without executing it.",
            aliases: &["rewrite"],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.rewrite"),
                resource_uri: None,
            },
            capabilities: &["diagnostic", "rewrite"],
            cluster: "execution",
            args: args(rewrite_schema()),
            results: default_results(),
            error_kinds: shell_errors(),
            arg_aliases: json!({ "command": ["cmd", "input", "script"], "argv": ["args"] }),
        },
        Operation {
            name: "tz_discover",
            description: "Report TokenZero filter and runtime readiness metadata.",
            aliases: &["discover"],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.discover"),
                resource_uri: None,
            },
            capabilities: &["diagnostic", "discovery"],
            cluster: "execution",
            args: args(no_args_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        // --- CodeMode MCP control tools ---
        Operation {
            name: "tz_execute_code",
            description: "Execute a TokenZero CodeMode recipe, JSON plan, or JavaScript plan.",
            aliases: &[],
            mutability: Mutability::WorkspaceMutating,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Heavy,
            ref_ownership: RefOwnership::Execution,
            cancellation: CancellationSemantics::Deadline,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: true,
                codemode_binding: None,
                resource_uri: None,
            },
            capabilities: &["codemode", "plan-execution", "sandboxed"],
            cluster: "codemode",
            args: args(execute_code_schema()),
            results: default_results(),
            error_kinds: shell_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_codemode_search",
            description: "Search the TokenZero CodeMode method catalog.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: true,
                codemode_binding: Some("codemode.search"),
                resource_uri: None,
            },
            capabilities: &["codemode", "catalog-search", "read-only"],
            cluster: "codemode",
            args: args(codemode_search_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_codemode_describe",
            description: "Describe a TokenZero CodeMode method or capabilities manifest.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: true,
                codemode_binding: Some("codemode.describe"),
                resource_uri: None,
            },
            capabilities: &["codemode", "catalog-describe", "read-only"],
            cluster: "codemode",
            args: args(codemode_describe_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "tz_report_tool_issue",
            description: "Record a field issue against a CodeMode/TokenZero tool name.",
            aliases: &["report_tool_issue", "report-tool-issue"],
            mutability: Mutability::StoreOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Canonical,
            exposure: SurfaceExposure {
                fastmcp_tool: true,
                codemode_mcp_tool: true,
                codemode_binding: None,
                resource_uri: None,
            },
            capabilities: &["diagnostic", "report"],
            cluster: "codemode",
            args: args(report_tool_issue_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({
                "tool": ["name", "tool_name", "surface"],
                "summary": ["message", "title"],
                "detail": ["body", "repro", "context"]
            }),
        },
        // --- CodeMode-only domain helpers (bindings without separate FastMCP tools) ---
        Operation {
            name: "zero.token.compact",
            description: "Store arbitrary text/data behind a tz:// recovery ref via ingest.",
            aliases: &["zero.compact"],
            mutability: Mutability::StoreOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::Blob,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.token.compact"),
                resource_uri: None,
            },
            capabilities: &["ingest", "exact-refs", "codemode"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": { "data": {} },
                "required": ["data"]
            })),
            results: ref_first_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "zero.token.compactMany",
            description: "Batch compact many payloads in one CodeMode step.",
            aliases: &[],
            mutability: Mutability::StoreOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Medium,
            ref_ownership: RefOwnership::Multi,
            cancellation: CancellationSemantics::Cooperative,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.token.compactMany"),
                resource_uri: None,
            },
            capabilities: &["ingest", "batch", "codemode"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": { "items": { "type": "array" } },
                "required": ["items"]
            })),
            results: ref_first_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "zero.token.expandMany",
            description: "Batch expand many tz:// refs in one CodeMode step.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Medium,
            ref_ownership: RefOwnership::Multi,
            cancellation: CancellationSemantics::Deadline,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.token.expandMany"),
                resource_uri: None,
            },
            capabilities: &["expand", "batch", "codemode"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": { "items": { "type": "array" } },
                "required": ["items"]
            })),
            results: ref_first_results(),
            error_kinds: expand_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "zero.token.dedupe",
            description: "Deduplicate JSON/string values while preserving first occurrence order.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.token.dedupe"),
                resource_uri: None,
            },
            capabilities: &["codemode"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": { "items": { "type": "array" } },
                "required": ["items"]
            })),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "zero.pipe",
            description: "Execute a sequence of operations with result threading (_prev auto-binding).",
            aliases: &[],
            mutability: Mutability::WorkspaceMutating,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Heavy,
            ref_ownership: RefOwnership::Multi,
            cancellation: CancellationSemantics::Deadline,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.pipe"),
                resource_uri: None,
            },
            capabilities: &["codemode", "pipeline"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": {
                    "steps": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "method": {"type": "string"},
                                "args": {"type": "array"}
                            },
                            "required": ["method"]
                        }
                    }
                },
                "required": ["steps"]
            })),
            results: default_results(),
            error_kinds: shell_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "zero.pick",
            description: "Extract specific keys from an object value.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.pick"),
                resource_uri: None,
            },
            capabilities: &["codemode"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": {
                    "source": {"type": "object"},
                    "keys": {"type": "array", "items": {"type": "string"}}
                },
                "required": ["source", "keys"]
            })),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "zero.filter_lines",
            description: "Filter lines in a text value by substring match.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.filter_lines"),
                resource_uri: None,
            },
            capabilities: &["codemode"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": {
                    "source": {},
                    "pattern": {"type": "string"}
                },
                "required": ["source", "pattern"]
            })),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "zero.compact_max",
            description: "Max compression with guaranteed byte-exact recovery.",
            aliases: &[],
            mutability: Mutability::StoreOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Medium,
            ref_ownership: RefOwnership::Blob,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.compact_max"),
                resource_uri: None,
            },
            capabilities: &["codemode", "exact-refs"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": { "data": {} },
                "required": ["data"]
            })),
            results: ref_first_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "zero.count",
            description: "Count lines in a text value or items in an array.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.count"),
                resource_uri: None,
            },
            capabilities: &["codemode"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": { "x": {} },
                "required": ["x"]
            })),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "zero.first",
            description: "Return the first line or array item, or the first n lines/items.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.first"),
                resource_uri: None,
            },
            capabilities: &["codemode"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": {
                    "x": {},
                    "n": {"type": "integer", "minimum": 1}
                },
                "required": ["x"]
            })),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "zero.verdict",
            description: "Return a compact one-line verdict object.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.verdict"),
                resource_uri: None,
            },
            capabilities: &["codemode"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": {
                    "ok": {},
                    "detail": {"type": "string"}
                },
                "required": ["ok"]
            })),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "zero.raw",
            description: "Opt one final-return value out of automatic ref-first compaction.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.raw"),
                resource_uri: None,
            },
            capabilities: &["codemode"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": { "value": {} },
                "required": ["value"]
            })),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "zero.count_tokens",
            description: "Count tokens, bytes, and lines in a value without storing it.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.count_tokens"),
                resource_uri: None,
            },
            capabilities: &["codemode", "introspection"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": { "data": {} },
                "required": ["data"]
            })),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "zero.assert",
            description: "Fail the plan immediately if condition is falsy.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("zero.assert"),
                resource_uri: None,
            },
            capabilities: &["codemode", "guard"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": {
                    "condition": {},
                    "message": {"type": "string"}
                },
                "required": ["condition"]
            })),
            results: default_results(),
            error_kinds: &[DomainErrorKind::Validation, DomainErrorKind::Policy],
            arg_aliases: json!({}),
        },
        Operation {
            name: "codemode.journalDoctor",
            description: "List unresolved plan journals and safe recovery advice.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::Session,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("codemode.journalDoctor"),
                resource_uri: None,
            },
            capabilities: &["codemode", "journal"],
            cluster: "codemode",
            args: args(no_args_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "codemode.journalInspect",
            description: "Inspect a redacted durable plan journal by execution id.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::Session,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("codemode.journalInspect"),
                resource_uri: None,
            },
            capabilities: &["codemode", "journal"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": { "execution_id": {"type": "string", "minLength": 1} },
                "required": ["execution_id"]
            })),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "codemode.journalResume",
            description: "Validate that an unresolved journal can be safely resumed.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::Session,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("codemode.journalResume"),
                resource_uri: None,
            },
            capabilities: &["codemode", "journal"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": { "execution_id": {"type": "string", "minLength": 1} },
                "required": ["execution_id"]
            })),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "codemode.journalRollback",
            description: "CAS-verified reverse-order rollback of an unresolved plan journal.",
            aliases: &[],
            mutability: Mutability::WorkspaceMutating,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Medium,
            ref_ownership: RefOwnership::Session,
            cancellation: CancellationSemantics::Cooperative,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("codemode.journalRollback"),
                resource_uri: None,
            },
            capabilities: &["codemode", "journal", "rollback"],
            cluster: "codemode",
            args: args(json!({
                "type": "object",
                "properties": { "execution_id": {"type": "string", "minLength": 1} },
                "required": ["execution_id"]
            })),
            results: default_results(),
            error_kinds: edit_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "codemode.limits",
            description: "Return active CodeMode sandbox, output, ref, and operation limits.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::CodemodeControl,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: Some("codemode.limits"),
                resource_uri: None,
            },
            capabilities: &["codemode", "limits"],
            cluster: "codemode",
            args: args(no_args_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        // --- Resources ---
        Operation {
            name: "resource.capabilities",
            description: "Discover tool clusters, aliases, protocol versions, and next recommended calls.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Resource,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: None,
                resource_uri: Some("resource://tokenzero/capabilities"),
            },
            capabilities: &["resource"],
            cluster: "resource",
            args: args(no_args_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "resource.tools",
            description: "Complete tool catalog with schemas and agent-oriented descriptions.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Resource,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: None,
                resource_uri: Some("resource://tokenzero/tools"),
            },
            capabilities: &["resource"],
            cluster: "resource",
            args: args(no_args_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "resource.roots",
            description: "File-system roots that read/find/tree/shell cwd operations may access.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Resource,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: None,
                resource_uri: Some("resource://tokenzero/roots"),
            },
            capabilities: &["resource", "policy"],
            cluster: "resource",
            args: args(no_args_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "resource.modes",
            description: "Accepted mode values for compacting, diagnostics, exact recovery, and pass-through.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Resource,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: None,
                resource_uri: Some("resource://tokenzero/modes"),
            },
            capabilities: &["resource"],
            cluster: "resource",
            args: args(no_args_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "resource.codemode",
            description: "Full CodeMode method catalog with signatures and discovery prefixes.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Resource,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: None,
                resource_uri: Some("resource://tokenzero/codemode"),
            },
            capabilities: &["resource", "codemode"],
            cluster: "resource",
            args: args(no_args_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "resource.cache",
            description: "Local recovery-cache and shell-output retention configuration.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Resource,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: None,
                resource_uri: Some("resource://tokenzero/cache"),
            },
            capabilities: &["resource", "cache"],
            cluster: "resource",
            args: args(no_args_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "resource.session_boot",
            description: "Bounded manifest+delta boot capsule and component token attribution.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::Session,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Resource,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: None,
                resource_uri: Some("resource://tokenzero/session-boot"),
            },
            capabilities: &["resource", "session"],
            cluster: "resource",
            args: args(no_args_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "resource.metrics",
            description: "Per-tool call counts, error counts, slow-call counts, and latency.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Resource,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: None,
                resource_uri: Some("resource://tokenzero/metrics"),
            },
            capabilities: &["resource", "telemetry"],
            cluster: "resource",
            args: args(no_args_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
        Operation {
            name: "resource.shell_contract",
            description: "Shell transport, command-success, exact-ref, timeout, and retry semantics.",
            aliases: &[],
            mutability: Mutability::ReadOnly,
            capability: CapabilityRequirement::Public,
            cost_class: CostClass::Cheap,
            ref_ownership: RefOwnership::None,
            cancellation: CancellationSemantics::None,
            migration: MigrationStatus::Resource,
            exposure: SurfaceExposure {
                fastmcp_tool: false,
                codemode_mcp_tool: false,
                codemode_binding: None,
                resource_uri: Some("resource://tokenzero/shell-contract"),
            },
            capabilities: &["resource", "shell", "policy"],
            cluster: "resource",
            args: args(no_args_schema()),
            results: default_results(),
            error_kinds: read_errors(),
            arg_aliases: json!({}),
        },
    ];

    ops.sort_by(|a, b| a.name.cmp(b.name));
    ops
}
