//! Microbenchmarks for TokenZero recovery hot-path functions.
//!
//! Run with: cargo bench -p tokenzero-recovery

use std::time::Duration;

use criterion::{Criterion, black_box, criterion_group, criterion_main};
use tempfile::TempDir;
use tokenzero_core::ContentType;
use tokenzero_recovery::{RecoveryConfig, RecoveryStore};

fn bench_persist(c: &mut Criterion) {
    let dir = TempDir::new().expect("temp dir");

    // Persist empty state (exercises lock + write + dir sync)
    c.bench_function("persist_empty", |b| {
        b.iter(|| {
            let path = dir.path().join(format!(
                "bench_empty_{}_{}.json",
                std::process::id(),
                black_box(0usize)
            ));
            let mut store = RecoveryStore::with_config(Some(path), RecoveryConfig::default());
            store.store_payload_deferred("key", ContentType::Code, None, None, None);
            black_box(store.persist_pending())
        })
    });

    // Persist with merge (exercises lock + load + merge + write + dir sync)
    c.bench_function("persist_merge", |b| {
        let path = dir
            .path()
            .join(format!("bench_merge_{}.json", std::process::id()));
        // Seed the file so persist exercises the merge path
        {
            let mut store =
                RecoveryStore::with_config(Some(path.clone()), RecoveryConfig::default());
            store.store_payload_deferred("existing", ContentType::Code, None, None, None);
            store.persist_pending().expect("seed persist");
        }
        b.iter(|| {
            let mut store =
                RecoveryStore::with_config(Some(path.clone()), RecoveryConfig::default());
            store.store_payload_deferred("key", ContentType::Code, None, None, None);
            black_box(store.persist_pending())
        })
    });
}

/// A config roomy enough that the pre-populated synthetic state below is
/// never evicted before it is persisted, so the bench measures persisting the
/// full payload at each target size rather than the eviction path.
fn roomy_config() -> RecoveryConfig {
    RecoveryConfig {
        max_blobs: 100_000,
        max_files: 100_000,
        max_units: 1_000_000,
        max_search_hits: 100_000,
        max_bytes: 64_000_000,
        max_load_bytes: 128_000_000,
        ..RecoveryConfig::default()
    }
}

/// Deterministic payload body of roughly `target_bytes`, seeded only by
/// `seed` so the generated bytes are identical between runs (no clocks, no
/// RNG). Mixes the seed into the text so distinct payloads are distinct blobs.
fn synthetic_payload(seed: usize, target_bytes: usize) -> String {
    // A fixed lexical base; repeated and salted with the seed until we reach
    // the target size. Deterministic across runs and machines.
    const BASE: &str =
        "fn recover(ref_id: &str) -> Option<String> { lookup(ref_id).map(decode) } // ";
    let mut out = String::with_capacity(target_bytes + BASE.len());
    let mut counter = 0usize;
    while out.len() < target_bytes {
        // Salt each line with seed+counter so the stream is unique but stable.
        out.push_str(BASE);
        out.push_str(&format!("seed={seed} line={counter}\n"));
        counter += 1;
    }
    out
}

/// Number of equal-sized payloads to reach roughly `total_bytes`. Each payload
/// is ~4 KiB so a size is built from many distinct blobs (closer to real
/// recovery state than one giant blob).
fn payload_plan(total_bytes: usize) -> (usize, usize) {
    const PER_PAYLOAD: usize = 4096;
    let count = (total_bytes / PER_PAYLOAD).max(1);
    (count, PER_PAYLOAD)
}

/// Build a store pre-populated with deterministic state of ~`total_bytes`,
/// persisted to `path` so its `disk_identity` is primed. Returns the store.
fn populated_store(path: std::path::PathBuf, total_bytes: usize) -> RecoveryStore {
    let mut store = RecoveryStore::with_config(Some(path), roomy_config());
    let (count, per) = payload_plan(total_bytes);
    for seed in 0..count {
        store.store_payload_deferred_batch(
            &synthetic_payload(seed, per),
            ContentType::Code,
            None,
            None,
            None,
        );
    }
    store.persist_pending().expect("seed persist");
    store
}

/// Pins the persist-path wins from BufWriter (5e94976), skip-reload
/// (fd61796), and the fsync policy (d0f9422). For each state size we measure:
///   (a) `store_payload` of one small payload on a freshly loaded store
///       (load + merge + atomic buffered write + sync) — the full persist path.
///   (b) a repeat `persist_pending` on unchanged in-memory state, which takes
///       the skip-reload branch (no reload/merge, just the buffered write).
fn bench_persist_path(c: &mut Criterion) {
    // ~0.5 MB, ~3 MB, ~8 MB of stored payloads.
    const SIZES: [(&str, usize); 3] = [
        ("0_5mb", 512 * 1024),
        ("3mb", 3 * 1024 * 1024),
        ("8mb", 8 * 1024 * 1024),
    ];

    let mut group = c.benchmark_group("persist_path");
    group.sample_size(10);
    group.measurement_time(Duration::from_secs(2));

    let dir = TempDir::new().expect("temp dir");
    let small = synthetic_payload(usize::MAX, 256);

    for (label, total_bytes) in SIZES {
        // (a) store + persist on a freshly loaded store: full persist path
        // (load existing state, merge, buffered atomic write, sync).
        {
            let seed_path = dir.path().join(format!("store_{label}.json"));
            // Prime the on-disk state once; each iteration loads it anew.
            let _ = populated_store(seed_path.clone(), total_bytes);
            group.bench_function(format!("store_payload_{label}"), |b| {
                b.iter(|| {
                    let mut store =
                        RecoveryStore::with_config(Some(seed_path.clone()), roomy_config());
                    black_box(store.store_payload(
                        black_box(&small),
                        ContentType::Code,
                        None,
                        None,
                        None,
                    ))
                    .expect("store_payload");
                })
            });
        }

        // (b) repeat persist on unchanged state: the skip-reload branch. The
        // store keeps a primed `disk_identity`, so each persist skips the
        // reload+merge and only re-writes the buffered snapshot.
        {
            let reuse_path = dir.path().join(format!("reuse_{label}.json"));
            let mut store = populated_store(reuse_path, total_bytes);
            // First persist already primed disk_identity; confirm the branch.
            store.persist_pending().expect("prime skip-reload");
            group.bench_function(format!("persist_unchanged_{label}"), |b| {
                b.iter(|| black_box(store.persist_pending()).expect("persist_unchanged"))
            });
        }
    }

    group.finish();
}

fn cache_footprint(path: &std::path::Path) -> u64 {
    let mut bytes = std::fs::metadata(path).map_or(0, |meta| meta.len());
    let mut sidecar_os = path.as_os_str().to_owned();
    sidecar_os.push(".blobs");
    let sidecar = std::path::PathBuf::from(sidecar_os);
    if let Ok(entries) = std::fs::read_dir(sidecar) {
        bytes += entries
            .filter_map(Result::ok)
            .filter_map(|entry| entry.metadata().ok())
            .filter(|meta| meta.is_file())
            .map(|meta| meta.len())
            .sum::<u64>();
    }
    bytes
}

/// Measures the durable cache footprint of repeatedly storing one deterministic
/// 220 KiB source as an explicit FileRef versus the ordinary Inline path.
fn measure_repeat_read_220kb_cache_bytes(c: &mut Criterion) {
    const PAYLOAD_BYTES: usize = 220 * 1024;
    const REPEATS: usize = 8;
    let dir = TempDir::new().expect("temp dir");
    let source = dir.path().join("repeat-read-220kb.txt");
    let file_cache = dir.path().join("file-ref-cache.json");
    let inline_cache = dir.path().join("inline-cache.json");
    std::fs::write(&source, vec![b'x'; PAYLOAD_BYTES]).expect("write deterministic source");

    let mut file_store = RecoveryStore::new(Some(file_cache.clone()));
    for _ in 0..REPEATS {
        file_store
            .store_file_backed_blob(&source, 1, 1, ContentType::Unknown)
            .expect("store FileRef");
    }
    let mut inline_store = RecoveryStore::new(Some(inline_cache.clone()));
    let payload = std::fs::read_to_string(&source).expect("read deterministic source");
    for _ in 0..REPEATS {
        inline_store
            .store_blob(&payload, ContentType::Unknown)
            .expect("store Inline");
    }

    let file_ref_cache_bytes = cache_footprint(&file_cache);
    let inline_cache_bytes = cache_footprint(&inline_cache);
    assert!(
        file_ref_cache_bytes < inline_cache_bytes,
        "FileRef footprint {file_ref_cache_bytes} must be below Inline {inline_cache_bytes}"
    );
    let evidence = serde_json::json!({
        "schema": "tokenzero.repeat-read-cache-bytes.v1",
        "payload_bytes": PAYLOAD_BYTES,
        "repeats": REPEATS,
        "file_ref_cache_bytes": file_ref_cache_bytes,
        "inline_cache_bytes": inline_cache_bytes,
        "measurement": "snapshot plus content-addressed sidecar files"
    });
    let evidence_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("benches/perf_hotspots/repeat_read_220kb_cache_bytes.json");
    std::fs::write(
        evidence_path,
        serde_json::to_vec_pretty(&evidence).expect("serialize evidence"),
    )
    .expect("write evidence");

    c.bench_function("measure_repeat_read_220kb_cache_bytes", |b| {
        b.iter(|| black_box((file_ref_cache_bytes, inline_cache_bytes)))
    });
}

criterion_group!(
    benches,
    bench_persist,
    bench_persist_path,
    measure_repeat_read_220kb_cache_bytes
);
criterion_main!(benches);
